### ISSUE TITLE
Importing rDNS v6 zone with nt_import.pl

### ISSUE THREAD

**Issue by hrnjan** [msimerson/NicTool#131] opened 2016-09-22 12:57 UTC
Hello,
first I would like to thank you for your great job with NicTool. Now to the point: I have successfully imported all of zones except rDNS IPv6 ones. I was looking all around tnpi forum for any clue without success (where my account has not been approved yet). 

Resending error: 
[root@cloud-2008 server]# ./bin/nt_import.pl --host 127.0.0.1 --user maitest --pass ****** --file /tmp/reverz.conf --type bind
loading type: bind

Starting import using: /tmp/reverz.conf
zone: e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa.     from    /tmp/ipv6
creating zone e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa.
created zone e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa. ( 333 )
NS : e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa   ns1.westmaster.com.
The 'zone_id' parameter (undef) to NicToolServer::Import::Base::nt_create_record was an 'undef', which is not one of the allowed types: scalar
 at lib/NicToolServer/Import/Base.pm line 126.
    NicToolServer::Import::Base::nt_create_record(undef, 'zone_id', undef, 'type', 'NS', 'name', '', 'address', 'ns1.westmaster.com.', ...) called at lib/NicToolServer/Import/BIND.pm line 109
    NicToolServer::Import::BIND::zr_ns('NicToolServer::Import::BIND::Conf_Parser=HASH(0x33c3490)', 'Net::DNS::RR::NS=HASH(0x2da5578)', 'e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa.') called at lib/NicToolServer/Import/BIND.pm line 73
    NicToolServer::Import::BIND::import_zone('NicToolServer::Import::BIND::Conf_Parser=HASH(0x33c3490)', 'e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa.', '/tmp/ipv6') called at lib/NicToolServer/Import/BIND.pm line 358
    NicToolServer::Import::BIND::Conf_Parser::handle_zone('NicToolServer::Import::BIND::Conf_Parser=HASH(0x33c3490)', 'e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa.', 'in', 'master', 'HASH(0x2a30c50)') called at /usr/local/share/perl5/BIND/Conf_Parser.pm line 762
    BIND::Conf_Parser::parse_zone('NicToolServer::Import::BIND::Conf_Parser=HASH(0x33c3490)') called at /usr/local/share/perl5/BIND/Conf_Parser.pm line 856
    BIND::Conf_Parser::parse_conf('NicToolServer::Import::BIND::Conf_Parser=HASH(0x33c3490)') called at /usr/local/share/perl5/BIND/Conf_Parser.pm line 887
    BIND::Conf_Parser::parse_fh('NicToolServer::Import::BIND::Conf_Parser=HASH(0x33c3490)', 'GLOB(0x2da4c60)') called at lib/NicToolServer/Import/BIND.pm line 54
    NicToolServer::Import::BIND::import_records('NicToolServer::Import::BIND=HASH(0x1f88280)', '/tmp/reverz.conf') called at ./bin/nt_import.pl line 61

bind test config file includes this: 
zone "e.3.2.0.0.3.4.0.1.0.a.2.ip6.arpa." {
        type master; allow-query { any; };
        file "/tmp/ipv6";
};

My zone:
$TTL 300
@       86400       IN      SOA    ns1.westmaster.com. support.master.cz.  (
                                      2016051601      ;Serial
                                      7200      ; Refresh
                                      1800       ; Retry
                                      1209600    ; Expire
                                      300 )   ; Minimum
@       172800                IN      NS    ns1.westmaster.com.
@       172800                IN      NS    ns2.westmaster.com.
@       172800                IN      NS    ns3.master.cz.
6.4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 PTR server.dathen.com.
7.4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 PTR mail.dathen.com.

Well, zone is created without any problem but after it its stucked on adding NS i guess. I would be very glad for any comment on this. 
Thank you !

**Comment by ryskaj** [comment] 2020-06-30 12:45
I ran into same issue here. Turns out it is caused by trailing dot in zone name. When new zone is added the trailing dot is removed but subsequent queries to db are executed with zone name containing trailing dot so it does not match and return empty set when querying for zone_id.

It should be easily fixed by removing that trailing dot, I fixed it for me by adding this to file server/lib/NicToolServer/Import/BIND.pm:
*** BIND.pm.orig	2020-06-30 08:40:11.380109245 -0400
--- BIND.pm	2020-06-30 08:40:40.249905557 -0400
***************
*** 50,55 ****
--- 50,56 ----
  sub import_zone {
      my ($self, $zone, $file) = @_;
  
+     $zone =~ s/\.$//; #remove trailing dot
      print "zone: $zone \tfrom\t$file\n";
  
      my $zonefile = Net::DNS::ZoneFile->new($file, $zone );

**Comment by ryskaj** [comment] 2020-06-30 12:46
```
*** BIND.pm.orig	2020-06-30 08:40:11.380109245 -0400
--- BIND.pm	2020-06-30 08:40:40.249905557 -0400
***************
*** 50,55 ****
--- 50,56 ----
  sub import_zone {
      my ($self, $zone, $file) = @_;
  
+     $zone =~ s/\.$//; #remove trailing dot
      print "zone: $zone \tfrom\t$file\n";
  
      my $zonefile = Net::DNS::ZoneFile->new($file, $zone );
```

**Comment by msimerson** [comment] 2020-07-07 04:05
Thanks for the patch @ryskaj , it is getting merged momentarily.

**Closed** 2020-07-07 04:05 UTC
